298 text field input autofill error
CRUKorg/cruk-react-components pull request #301
Opened 2021-09-16 12:53 UTC by juff

Created a new styled component to wrap around the TextField component and fix the disappearing isValid icon

2021-09-16 13:03 UTC, juff commented
@Develliot @eardenercruk @hom-bahrani i have run prettier but still looks like there are issues on the checks

2021-09-17 14:36 UTC, Develliot commented
fixes #298

2021-09-17 14:41 UTC, Develliot approved these changes

2021-09-17 14:42 UTC, Develliot requested changes
snaps are broken

2021-09-20 09:10 UTC, merged