Disabled checkbox styles
CRUKorg/cruk-react-components pull request #695
Opened 2023-06-20 12:28 UTC by JanGanaCode

This was done to match disabled styles of other components.

`from`:
![Screenshot 2023-06-20 at 13 15 36](https://github.com/CRUKorg/cruk-react-components/assets/25926950/8d1bfce6-080e-4f44-83d1-8d3e5ac4c382)

`to`:
![Screenshot 2023-06-20 at 13 22 21](https://github.com/CRUKorg/cruk-react-components/assets/25926950/8ddf0c8d-67a8-4252-8655-d733343212db)

<hr>

`disabled Select`:
![Screenshot 2023-06-20 at 13 24 27](https://github.com/CRUKorg/cruk-react-components/assets/25926950/2029e527-cb10-4449-be16-68e7b4d105e1)

`disabled TextField`:
![Screenshot 2023-06-20 at 13 24 43](https://github.com/CRUKorg/cruk-react-components/assets/25926950/a365bf33-527a-4e8c-bbcf-00a85dc5b2ce)

2023-06-20 12:35 UTC, rushicruk requested changes
Good catch :) But I just wondering can we do same for the Radio too?

<img width="477" alt="Screenshot 2023-06-20 at 13 34 03" src="https://github.com/CRUKorg/cruk-react-components/assets/106080695/7895f5b6-ab00-41b7-b7d4-f890f5d658b2">

2023-06-20 13:15 UTC, samkio approved these changes
Radio style can be done in a seperate commit to keep atomicity (if need be).

2023-06-20 14:49 UTC, JanGanaCode commented
> Good catch :) But I just wondering can we do same for the Radio too?
> 
> <img alt="Screenshot 2023-06-20 at 13 34 03" width="477" src="https://user-images.githubusercontent.com/106080695/247115939-7895f5b6-ab00-41b7-b7d4-f890f5d658b2.png">

Made the changes in #696 .

2023-06-20 15:09 UTC, samkio requested changes

2023-06-20 15:09 UTC, samkio commented on src/components/Checkbox/styles.ts
> +  border-color: ${({ theme, disabled }: StyledLabelProps) =>
https://github.com/CRUKorg/cruk-react-components/pull/696#discussion_r1235414252

2023-06-20 15:32 UTC, samkio approved these changes

2023-06-21 13:53 UTC, Develliot commented
fixes #675

2023-06-21 13:53 UTC, closed without merging

2023-06-21 13:56 UTC, Develliot commented
Actually this missed overrides a previous styled with an error with red border