Disabled radio styles
CRUKorg/cruk-react-components pull request #696
Opened 2023-06-20 14:49 UTC by JanGanaCode

This was done to match disabled styles of other components.

`from`:
![Screenshot 2023-06-20 at 15 46 44](https://github.com/CRUKorg/cruk-react-components/assets/25926950/4d0cf6d9-8b59-45cc-823b-7fae058d7ff3)

`to`:
![Screenshot 2023-06-20 at 15 46 03](https://github.com/CRUKorg/cruk-react-components/assets/25926950/30eec996-8c21-4ad9-91ed-156c2d13876c)

<hr>

`disabled Select`:
![Screenshot 2023-06-20 at 13 24 27](https://github.com/CRUKorg/cruk-react-components/assets/25926950/2029e527-cb10-4449-be16-68e7b4d105e1)

`disabled TextField`:
![Screenshot 2023-06-20 at 13 24 43](https://github.com/CRUKorg/cruk-react-components/assets/25926950/a365bf33-527a-4e8c-bbcf-00a85dc5b2ce)

2023-06-20 15:08 UTC, samkio requested changes

2023-06-20 15:08 UTC, samkio commented on src/components/Radio/styles.ts
> +  ${({ theme, disabled }: StyledLabelProps) =>
Is this the right type? Should it be `ThemeProp & DisabledProp` (same applies for the Checkbox change actuall)

2023-06-20 15:49 UTC, samkio approved these changes

2023-06-21 13:54 UTC, Develliot commented
fixes #675

2023-06-21 13:59 UTC, Develliot commented
This is overriding a previous style for error state, I'm closing because I didn't see this PR and have just written a fix my apologies.   Please reference but number in PR so I can see if the ticket has been done from the tickets themselves

2023-06-21 13:59 UTC, closed without merging